try catch block
--> The main code is inside the `try` block. While executing th `try` block, if any error occurs, it goes to the `catch` block. The `catch` block handles the errors as per the catch statements.

--> if no error occurs, the code inside the `try` block is executed and the `catch` block is skipped.

try {
//body of try
} catch (error) {
// body of catch
}
